### ISSUE TITLE
entities dont show on/off values when creating automation

### ISSUE THREAD

**Issue by Bebeone111** [rnovacek/homeassistant_cz_energy_spot_prices#31] opened 2023-07-27 21:43 UTC
When using conditions in automation, I dont see on/off value of sensors. I can only see not available/unknown

<img width="1470" alt="Snímek obrazovky 2023-07-27 v 23 40 11" src="https://github.com/rnovacek/homeassistant_cz_energy_spot_prices/assets/84333616/83ad26af-88d2-433d-a481-d1c607647692">

**Comment by kkoouu** [comment] 2023-07-28 08:45
and what's the actual value ? In last days these values were not working for me and were undefined, I tried reload/restart and integration reinstall. However you can enter on/off value manually in the automation.

**Comment by Bebeone111** [comment] 2023-07-28 09:02
There are more entities, the actual value is off or on. I see it in the main dashboard. Going to try the manual input and reinstall. Restart didnt fix it.

**Comment by kkoouu** [comment] 2023-07-28 09:04
But for sure this is not an integration issue of not showing popup values when using automation ...

**Comment by Bebeone111** [comment] 2023-07-28 09:16
Manual input worked. Im a novice in HA, so sorry for maybe stupid question and thanks for help!

**Comment by rnovacek** [comment] 2023-09-12 09:50
The problem is that the sensor is called `sensor.spot_electricity_is_cheapest_X_hours_block` but HA would need the entity to be called `binary_sensor.X` to add the On/Off values there . This would be a breaking change and I'm not quite sure if it is worth it.

**Comment by rpajik** [comment] 2023-11-10 06:44
I believe, that it help a lot to fix this issue. I understand, that it is breaking changes, so what about to duplicate sensors for some time? It's up to you, how long the period will be.

**Comment by kukulich** [comment] 2024-11-10 21:22
Fixed in #68

**Closed** 2024-11-10 22:36 UTC
